

import urllib
import json
import wordParser

def getAllEntries():
    dishDicts = [] 
    try: 
       data = getLiveData()
       dishDicts = data['dishes']
       if len(dicts) == 0: 
          raise Error("empty dictionary list")
    except:
       dishDicts = getCachedData()
    # Normalize the meal and dish names to exclude inter-word punctuation
    for dishDict in dishDicts: 
        dishDict['meal'] = ' '.join(wordParser.wordsFromString(dishDict['meal']))
        dishDict['dish'] = ' '.join(wordParser.wordsFromString(dishDict['dish']))
    return dishDicts

def getLiveData():
    dateString = "0000-01-01"
    dishList = []
    try:
        data = urllib.urlencode({})
        response = urllib.urlopen("http://cs.wellesley.edu/~cs118/cgi-bin/wellesley-fresh/wellesleyFresh.cgi", data)
        jsonList = json.loads(response.read())
        dateString = jsonList[0] # first element of list                                                                 
        dishList = jsonList[1:] # all remaining elements of list                                                         
    except:
        print("***ERROR: can't access CS118 Wellesley Fresh server. Contact Lyn ***")
    dishDicts = map(lambda e: {'hall':e[0].encode('ascii', 'ignore'),
                               'day':e[1].encode('ascii', 'ignore'),
                               'meal':e[2].encode('ascii', 'ignore'),
                               'dish':e[3].encode('ascii', 'ignore')},
                    dishList) # Return a list of dictionaries, converting unicode to ascii strings.                      
    return {'date': dateString, 'dishes': dishDicts}

def getCachedData():
    entryLists = cachedDishes
    #print("There's a problem accessing the Wellesley Fresh web database.")
    #print("Instead using a cached copy of the database from an earlier date.")
    entryDicts = map(lambda e: {'hall':e[0].encode('ascii', 'ignore'),
                                'day':e[1].encode('ascii', 'ignore'),
                                'meal':e[2].encode('ascii', 'ignore'),
                                'dish':e[3].encode('ascii', 'ignore')},
                     entryLists) # Return a list of dictionaries, converting unicode to ascii strings.
    return entryDicts

# Cached list of dishes from earlier date in case something goes wrong with
# obtaing list from web database
cachedDishes = [[u'Bae Pao Lu Chow', u'Monday', u'Continental Breakfast', u'Waffle Bar'],
                [u'Bae Pao Lu Chow', u'Monday', u'Soup', u'Ham & Cabbage'],
                [u'Bae Pao Lu Chow', u'Monday', u'Homestyle Dinner', u'Macaroni & Cheese'],
                [u'Bae Pao Lu Chow', u'Monday', u'Deli', u'Veggie Club Sandwich'],
                [u'Bae Pao Lu Chow', u'Tuesday', u'Pure', u'Vegetable Kabobs'],
                [u'Bae Pao Lu Chow', u'Tuesday', u'Fusion Lunch', u'Apple Ginger Vin.'],
                [u'Bae Pao Lu Chow', u'Tuesday', u'Deli', u'Beef & Cheddar'],
                [u'Bae Pao Lu Chow', u'Wednesday', u'Pizza', u'Squash'],
                [u'Bae Pao Lu Chow', u'Thursday', u'Continental Breakfast', u'Waffle Bar'],
                [u'Bae Pao Lu Chow', u'Thursday', u'Homestyle Dinner', u'Peas'],
                [u'Bae Pao Lu Chow', u'Friday', u'Pure', u'Wrapped In Lettuce'],
                [u'Bae Pao Lu Chow', u'Friday', u'Homestyle Dinner', u'Cauliflower'],
                [u'Bae Pao Lu Chow', u'Friday', u'Deli', u'Tuna Salad'],
                [u'Bae Pao Lu Chow', u'Saturday', u'Pizza', u'Arugula & Shaved Parm'],
                [u'Bae Pao Lu Chow', u'Sunday', u'Continental Breakfast', u'Fresh Fruit'],
                [u'Bae Pao Lu Chow', u'Sunday', u'Fusion Lunch', u'Home Fries'],
                [u'Bates', u'Monday', u'Breakfast', u'Scrambled Eggs Or Whites-Veg'],
                [u'Bates', u'Tuesday', u'Homestyle Dinner', u'Stuffed Meatloaf'],
                [u'Bates', u'Tuesday', u'Pasta', u'Asian Sauces'],
                [u'Bates', u'Wednesday', u'Homestyle Dinner', u'Roasted Root Vegetables'],
                [u'Bates', u'Thursday', u'Deli', u'Egg Salad'],
                [u'Bates', u'Friday', u'Homestyle Lunch', u'Hungarian Goulash'],
                [u'Bates', u'Saturday', u'Continental Breakfast', u'Steel Cut Oatmeal'],
                [u'Bates', u'Sunday', u'Brunch Homestyle', u'Steamed Carrots'],
                [u'Bates', u'Sunday', u'Fusion', u'Sundae Sundays'],
                [u'Pomeroy', u'Monday', u'Breakfast', u'Waffle Bar'],
                [u'Pomeroy', u'Monday', u'Pasta Bar', u'Tossed In Penne'],
                [u'Pomeroy', u'Tuesday', u'Deli', u'Sundried Tomatoes'],
                [u'Pomeroy', u'Tuesday', u'Dinner', u'Roasted Redskins'],
                [u'Pomeroy', u'Wednesday', u'Breakfast', u'Yogurts'],
                [u'Pomeroy', u'Wednesday', u'Lunch', u'Refried Beans'],
                [u'Pomeroy', u'Thursday', u'Lunch', u'Socca'],
                [u'Pomeroy', u'Friday', u'Breakfast', u'Scrambled Eggs'],
                [u'Pomeroy', u'Friday', u'Deli', u'Tabbouleh'],
                [u'Pomeroy', u'Friday', u'Dinner', u'Cranberry Sauce'],
                [u'Pomeroy', u'Saturday', u'Soup of the Day', u'Chick Rice with Dumping'],
                [u'Pomeroy', u'Sunday', u'Continental Breakfast', u'Oatmeal Bar'],
                [u'Pomeroy', u'Sunday', u'Brunch', u'Scramble Eggs'],
                [u'Stone Davis', u'Monday', u'Breakfast', u'Hard Boiled Eggs'],
                [u'Stone Davis', u'Monday', u'Lunch', u'Broccoli'],
                [u'Stone Davis', u'Monday', u'MYO Deli', u'Italian Sub'],
                [u'Stone Davis', u'Tuesday', u'Lunch', u'Biscuits'],
                [u'Stone Davis', u'Tuesday', u'Pizza', u'White'],
                [u'Stone Davis', u'Wednesday', u'Breakfast', u'Scrambled Eggs'],
                [u'Stone Davis', u'Wednesday', u'Lunch', u'Edamame'],
                [u'Stone Davis', u'Wednesday', u'Pasta', u'Garlic Butter'],
                [u'Stone Davis', u'Thursday', u'Breakfast', u'Fried Egg Sandwich'],
                [u'Stone Davis', u'Thursday', u'Soup', u'Black Bean Soup'],
                [u'Stone Davis', u'Thursday', u'MYO Deli', u'Turkey, Ham, Salami'],
                [u'Stone Davis', u'Friday', u'Breakfast', u'Egg & Cheese Croissant'],
                [u'Stone Davis', u'Friday', u'Pizza', u'Spinach & Garlic'],
                [u'Tower', u'Monday', u'Homestyle Lunch', u'Egg Noodles'],
                [u'Tower', u'Monday', u'Vegan & Grain Bar', u'Crispy Tofu Pesto'],
                [u'Tower', u'Monday', u'Deli', u'American, Cheddar, Swiss'],
                [u'Tower', u'Tuesday', u'Vegan & Grain Bar', u'Seitan Picatta'],
                [u'Tower', u'Tuesday', u'Deli', u'American, Provolone, Muenster'],
                [u'Tower', u'Wednesday', u'Homestyle Lunch', u'Vegetable Medley-V'],
                [u'Tower', u'Wednesday', u'Vegan & Grain Bar', u'Spicy Tofu'],
                [u'Tower', u'Wednesday', u'Deli', u'Lettuce, Tomato, Onion, Pickles'],
                [u'Tower', u'Thursday', u'Homestyle Lunch', u'Peas'],
                [u'Tower', u'Thursday', u'Vegan & Grain Bar', u'"Chicken" Tikka Masala'],
                [u'Tower', u'Thursday', u'Deli', u'Lettuce, Tomato, Onion, Pickles'],
                [u'Tower', u'Friday', u'Homestyle Lunch', u'Grilled Crabcake'],
                [u'Tower', u'Friday', u'Vegan & Grain Bar', u'Rice & Beans'],
                [u'Tower', u'Friday', u'Deli', u'Turkey, Ham, Tuna Salad'],
                [u'Tower', u'Saturday', u'Homestyle Dinner', u'Garlic Bread-Veg'],
                [u'Tower', u'Saturday', u'Deli', u'Closed'],
                [u'Tower', u'Sunday', u'Brunch', u'Peas'],
                [u'Tower', u'Sunday', u'Vegan & Grain Bar', u'Sage Chickpeas'],
                [u'Tower', u'Sunday', u'Pasta', u'Giardineira'],
                [u'Bae Pao Lu Chow', u'Monday', u'Continental Breakfast', u'Oatmeal Bar'],
                [u'Bae Pao Lu Chow', u'Monday', u'Pizza', u'Cheese Pizza'],
                [u'Bae Pao Lu Chow',
                 u'Monday',
                 u'Homestyle Dinner',
                 u'Dijon Roasted Potatoes 4643'],
                [u'Bae Pao Lu Chow', u'Tuesday', u'Continental Breakfast', u'Waffle Bar'],
                [u'Bae Pao Lu Chow', u'Tuesday', u'Soup', u'Creamy Onion & Leek Potage'],
                [u'Bae Pao Lu Chow', u'Wednesday', u'Pizza', u'Creamed Spinach'],
                [u'Bae Pao Lu Chow', u'Wednesday', u'Homestyle Dinner', u'Broccoli Alfredo'],
                [u'Bae Pao Lu Chow', u'Thursday', u'Pizza', u'Thai Shrimp'],
                [u'Bae Pao Lu Chow', u'Thursday', u'Deli', u'Sliced Turkey'],
                [u'Bae Pao Lu Chow', u'Friday', u'Homestyle Dinner', u'Gravy'],
                [u'Bae Pao Lu Chow', u'Saturday', u'Continental Breakfast', u'Waffle Bar'],
                [u'Bae Pao Lu Chow', u'Saturday', u'Grill', u'Black & Blue Burger'],
                [u'Bae Pao Lu Chow',
                 u'Saturday',
                 u'Homestyle Dinner',
                 u"Pork Sheppard's Pie"],
                [u'Bae Pao Lu Chow',
                 u'Sunday',
                 u'Continental Breakfast',
                 u'Yogurt & Cottage Cheese'],
                [u'Bates', u'Monday', u'Homestyle Lunch', u'Roasted Red Potatoes'],
                [u'Bates', u'Monday', u'Fusion', u'Field Greens with Cranberries/'],
                [u'Bates', u'Tuesday', u'Homestyle Dinner', u'Mustard Greens'],
                [u'Bates', u'Wednesday', u'Pasta', u'Bean & Rice Bar'],
                [u'Bates', u'Wednesday', u'Deli', u'3 Cheeses-Veg'],
                [u'Bates', u'Thursday', u'Daily Soups', u'Fish Chowder'],
                [u'Bates', u'Friday', u'Global Grill', u'Internarional Grilled Chicken'],
                [u'Bates', u'Friday', u'Deli', u'Seafood Salad'],
                [u'Bates', u'Saturday', u'Brunch Homestyle', u'Breakfast Quesadillas'],
                [u'Bates', u'Saturday', u'Pasta', u'Marinara-V'],
                [u'Bates', u'Sunday', u'Deli', u'Chefs Choice'],
                [u'Pomeroy', u'Tuesday', u'Deli', u'Tabbouleh'],
                [u'Pomeroy', u'Wednesday', u'Breakfast', u'Scrambled Eggs'],
                [u'Pomeroy', u'Wednesday', u'Soup of the Day', u'Chickpea Tomatoes & Bread'],
                [u'Pomeroy', u'Wednesday', u'Lunch', u'Black Bean & Corn'],
                [u'Pomeroy', u'Thursday', u'Breakfast', u'Waffle Bar'],
                [u'Pomeroy', u'Thursday', u'Lunch', u'Herbed White Beans'],
                [u'Pomeroy', u'Friday', u'Breakfast', u'Waffle Bar'],
                [u'Pomeroy', u'Friday', u'Lunch', u'"Beef" Stew'],
                [u'Pomeroy', u'Friday', u'Dinner', u'Candied Yams'],
                [u'Pomeroy', u'Saturday', u'Brunch', u'Wilted Spinach'],
                [u'Pomeroy',
                 u'Sunday',
                 u'Continental Breakfast',
                 u'Assorted Breakfast Pastry'],
                [u'Pomeroy', u'Sunday', u'Brunch', u'Seitan & Red Pepper'],
                [u'Pomeroy', u'Sunday', u'Dinner', u'Swiss Chard'],
                [u'Stone Davis', u'Monday', u'Breakfast', u'Egg Whites to Order'],
                [u'Stone Davis', u'Monday', u'Lunch', u'Spanish Rice'],
                [u'Stone Davis', u'Tuesday', u'Breakfast', u'Hard Boiled Eggs'],
                [u'Stone Davis', u'Tuesday', u'Dinner', u'Teriyaki Roti Chicken'],
                [u'Stone Davis', u'Tuesday', u'Davis Grille', u'Black Bean Burger'],
                [u'Stone Davis', u'Thursday', u'Lunch', u'Rolls'],
                [u'Stone Davis', u'Thursday', u'Pizza', u'Pork Tontasku'],
                [u'Stone Davis', u'Friday', u'Lunch', u'Herb Butter Ravioli'],
                [u'Stone Davis', u'Friday', u'Davis Grille', u'Halal Burgers'],
                [u'Tower', u'Monday', u'Breakfast', u'Steel Cut Oatmeal-V'],
                [u'Tower', u'Monday', u'Homestyle Dinner', u'Steamed Carrots'],
                [u'Tower', u'Monday', u'Grill', u'Closed'],
                [u'Tower',
                 u'Monday',
                 u'Allergy Station',
                 u'Plain Ground Beef Or Turkey-Lunch'],
                [u'Tower', u'Tuesday', u'Homestyle Lunch', u'Garlic Bread-Veg'],
                [u'Tower', u'Tuesday', u'Grill', u'Buffalo Chicken Sandwich'],
                [u'Tower', u'Tuesday', u'Allergy Station', u'G.F. Pasta with Marinara-Lunch'],
                [u'Tower', u'Wednesday', u'Homestyle Lunch', u'Yellow Rice'],
                [u'Tower', u'Wednesday', u'Grill', u'Production Day'],
                [u'Tower', u'Wednesday', u'Allergy Station', u'Baked Chicken-Dinner'],
                [u'Tower', u'Thursday', u'Homestyle Lunch', u'Spoon Bread'],
                [u'Tower', u'Thursday', u'Grill', u'Onion Rings'],
                [u'Tower', u'Friday', u'Homestyle Lunch', u'Green Beans-V'],
                [u'Tower', u'Friday', u'Vegan & Grain Bar', u'Tvp Meatloaf'],
                [u'Tower', u'Saturday', u'Brunch', u'Shredded Hash Browns-V'],
                [u'Tower', u'Saturday', u'Pizza', u'Closed'],
                [u'Tower',
                 u'Saturday',
                 u'Allergy Station',
                 u'G.F. Pasta with Marinara-Dinner'],
                [u'Tower', u'Sunday', u'Brunch', u'Rice Pilaf'],
                [u'Tower', u'Sunday', u'Pasta', u'Marinara Sauce-V'],
                [u'Tower', u'Sunday', u'Allergy Station', u'Baked Ham-Lunch'],
                [u'Bae Pao Lu Chow',
                 u'Monday',
                 u'Continental Breakfast',
                 u'Hard Boiled Eggs'],
                [u'Bae Pao Lu Chow', u'Monday', u'Pure', u'Zucchini Noodles with'],
                [u'Bae Pao Lu Chow',
                 u'Tuesday',
                 u'Continental Breakfast',
                 u'Hard Boiled Eggs'],
                [u'Bae Pao Lu Chow', u'Thursday', u'Continental Breakfast', u'Pastries'],
                [u'Bae Pao Lu Chow', u'Thursday', u'Pizza', u"Chef's Daily Artisan"],
                [u'Bae Pao Lu Chow', u'Thursday', u'Fusion Lunch', u'Wild Rice Pilaf'],
                [u'Bae Pao Lu Chow', u'Thursday', u'Deli', u'Corned Beef'],
                [u'Bae Pao Lu Chow',
                 u'Friday',
                 u'Continental Breakfast',
                 u'Hard Boiled Eggs'],
                [u'Bae Pao Lu Chow', u'Friday', u'Fusion Lunch', u'Chipotle Mashed Potatoes'],
                [u'Bae Pao Lu Chow', u'Friday', u'Deli', u'Sliced Turkey'],
                [u'Bae Pao Lu Chow', u'Saturday', u'Grill', u'Lunch-French Toast'],
                [u'Bae Pao Lu Chow', u'Saturday', u'Homestyle Dinner', u'Roasted Yams'],
                [u'Bae Pao Lu Chow', u'Sunday', u'Grill', u'Lunch-Omelets'],
                [u'Bae Pao Lu Chow', u'Sunday', u'Homestyle Dinner', u'Garlic Chicken'],
                [u'Bates', u'Monday', u'Breakfast', u'Steel Cut Oatmeal'],
                [u'Bates', u'Monday', u'Homestyle Dinner', u'BBQ Pork Tips'],
                [u'Bates', u'Tuesday', u'Homestyle Dinner', u'Scalloped Potatoes'],
                [u'Bates', u'Wednesday', u'Fusion', u'Pineapple Fried Rice'],
                [u'Bates', u'Thursday', u'Breakfast', u'Scrambled Eggs Or Whites-Veg'],
                [u'Bates', u'Saturday', u'Brunch Homestyle', u'Turkey Sausage'],
                [u'Bates', u'Saturday', u'Deli', u'Chefs Choice'],
                [u'Bates', u'Sunday', u'Brunch Grill', u'Spicy Homefries'],
                [u'Pomeroy', u'Monday', u'Breakfast', u'Red Bliss Home Fries'],
                [u'Pomeroy', u'Tuesday', u'Breakfast', u'Curried Tofu Scramble'],
                [u'Pomeroy', u'Tuesday', u'Lunch', u'Honey Glazed Carrots'],
                [u'Pomeroy', u'Wednesday', u'Pasta Bar', u'Edamame'],
                [u'Pomeroy', u'Wednesday', u'Dinner', u'Lemon & Eggplant Risotto'],
                [u'Pomeroy', u'Thursday', u'Breakfast', u'Oatmeal Bar'],
                [u'Pomeroy', u'Thursday', u'Dinner', u'Mock Meat Loaf'],
                [u'Pomeroy', u'Friday', u'Breakfast', u'Maple Glazed Seitan'],
                [u'Pomeroy', u'Friday', u'Lunch', u'Fresh Chips'],
                [u'Pomeroy', u'Saturday', u'Pasta Bar @ Dinner', u'Pasta & Vegetable'],
                [u'Pomeroy', u'Saturday', u'Dinner', u'White Pizza'],
                [u'Pomeroy', u'Sunday', u'Continental Breakfast', u'Cottage Cheese'],
                [u'Pomeroy', u'Sunday', u'Brunch', u'Twist Baked Potatoes'],
                [u'Stone Davis', u'Monday', u'Dinner', u'Peas'],
                [u'Stone Davis', u'Tuesday', u'Breakfast', u'Waffle Bar'],
                [u'Stone Davis',
                 u'Wednesday',
                 u'Breakfast',
                 u'Country Sliced Potatoes (Veg)'],
                [u'Stone Davis', u'Wednesday', u'Dinner', u'Cauliflower'],
                [u'Stone Davis', u'Thursday', u'Breakfast', u'Hard Boiled Eggs'],
                [u'Stone Davis', u'Thursday', u'Lunch', u'Egg Noodles'],
                [u'Stone Davis', u'Thursday', u'MYO Deli', u'Cold Stuffing'],
                [u'Stone Davis', u'Friday', u'Lunch', u'Corn Bread'],
                [u'Stone Davis', u'Friday', u'Davis Grille', u'Fish Cakes'],
                [u'Tower', u'Monday', u'Breakfast', u'Red Bliss Home Fries-V'],
                [u'Tower', u'Monday', u'Composed Salad Bar', u'Broccoli Salad-V'],
                [u'Tower', u'Tuesday', u'Breakfast', u'Egg & Cheese Bagel'],
                [u'Tower', u'Tuesday', u'Homestyle Dinner', u'Bok Choy'],
                [u'Tower', u'Tuesday', u'Composed Salad Bar', u'Med. Pasta Salad-V'],
                [u'Tower', u'Wednesday', u'Breakfast', u'Steel Cut Oatmeal-V'],
                [u'Tower', u'Wednesday', u'Homestyle Dinner', u'Okra'],
                [u'Tower', u'Wednesday', u'Composed Salad Bar', u'Barley Salad-V'],
                [u'Tower', u'Thursday', u'Breakfast', u'Egg & Cheese Croissant'],
                [u'Tower', u'Thursday', u'Homestyle Dinner', u'Biscuits & Gravy'],
                [u'Tower', u'Thursday', u'Composed Salad Bar', u'Tabouleh-V'],
                [u'Tower', u'Friday', u'Breakfast', u'Steel Cut Oatmeal-V'],
                [u'Tower', u'Friday', u'Homestyle Dinner', u'Korean BBQ'],
                [u'Tower', u'Friday', u'Vegan & Grain Bar', u'Cilantro Lime Tempeh'],
                [u'Tower', u'Saturday', u'Pasta', u'Marinara Sauce-V'],
                [u'Tower', u'Sunday', u'Continental Breakfast', u'Hardboiled Eggs'],
                [u'Tower', u'Sunday', u'Homestyle Dinner', u'Mashed Potatoes-Veg'],
                [u'Bae Pao Lu Chow', u'Monday', u'Continental Breakfast', u'Fresh Fruit'],
                [u'Bae Pao Lu Chow', u'Monday', u'Fusion Lunch', u'Biscuits'],
                [u'Bae Pao Lu Chow', u'Tuesday', u'Pizza', u'Roasted Veg & Pesto'],
                [u'Bae Pao Lu Chow', u'Tuesday', u'Grill', u'Salt & Vinegar Slaw'],
                [u'Bae Pao Lu Chow', u'Tuesday', u'Deli', u'Sliced Ham'],
                [u'Bae Pao Lu Chow', u'Wednesday', u'Pure', u'Reuben Burritos'],
                [u'Bae Pao Lu Chow', u'Thursday', u'Homestyle Dinner', u'Butter Nut Squash'],
                [u'Bae Pao Lu Chow', u'Friday', u'Pizza', u'Cheese Pizza'],
                [u'Bae Pao Lu Chow', u'Friday', u'Fusion Lunch', u'Green Beans'],
                [u'Bae Pao Lu Chow', u'Friday', u'Deli', u'Sliced Ham'],
                [u'Bae Pao Lu Chow', u'Saturday', u'Continental Breakfast', u'Fresh Fruit'],
                [u'Bae Pao Lu Chow', u'Saturday', u'Fusion Lunch', u'Cheese Frittata'],
                [u'Bae Pao Lu Chow', u'Saturday', u'Homestyle Dinner', u'Coffee Bbq Tempeh'],
                [u'Bae Pao Lu Chow', u'Sunday', u'Homestyle Dinner', u'Barley Pilaf'],
                [u'Bates', u'Monday', u'Pasta', u'Marinara'],
                [u'Bates', u'Tuesday', u'Breakfast', u'Hardboiled Eggs-Veg'],
                [u'Bates', u'Tuesday', u'Homestyle Lunch', u'Chinese Sausage'],
                [u'Bates', u'Tuesday', u'Global Grill', u'Tofu Curry'],
                [u'Bates', u'Tuesday', u'Deli', u'Ham Salad'],
                [u'Bates', u'Thursday', u'Homestyle Lunch', u'Wilted Kale'],
                [u'Bates', u'Friday', u'Homestyle Dinner', u'Poached Salmon'],
                [u'Bates', u'Friday', u'Pasta', u'Egg Noodles/Thai Peanut'],
                [u'Bates', u'Saturday', u'Brunch Homestyle', u'Steamed Summer Squash'],
                [u'Bates', u'Saturday', u'Homestyle Dinner', u'Steamed Broccoli'],
                [u'Bates',
                 u'Sunday',
                 u'Continental Breakfast',
                 u'Scrambled Eggs Or Whites-Veg'],
                [u'Bates', u'Sunday', u'Homestyle Dinner', u'Roasted Butternut Squash'],
                [u'Pomeroy', u'Monday', u'Lunch', u'Vegan Meatball Calzone'],
                [u'Pomeroy', u'Tuesday', u'Breakfast', u'Yogurts'],
                [u'Pomeroy', u'Tuesday', u'Dinner', u'Roasted Vegetable Manicottis'],
                [u'Pomeroy', u'Wednesday', u'Deli', u'Moroccan Couscous Salad'],
                [u'Pomeroy', u'Thursday', u'Breakfast', u'Breakfast "Sausage" Patties'],
                [u'Pomeroy', u'Thursday', u'Deli', u'3 Bean Salad'],
                [u'Pomeroy', u'Friday', u'Breakfast', u'Yogurts'],
                [u'Pomeroy', u'Saturday', u'Continental Breakfast', u'Fresh Fruit'],
                [u'Pomeroy', u'Saturday', u'Deli', u'Tabbouleh'],
                [u'Stone Davis', u'Monday', u'Breakfast', u'Turkey Sausage Links'],
                [u'Stone Davis', u'Tuesday', u'Breakfast', u'Steel Cut Oats Bar (V)'],
                [u'Stone Davis', u'Tuesday', u'MYO Deli', u'Turkey, Ham, Bologna'],
                [u'Stone Davis', u'Wednesday', u'Breakfast', u'Steel Cut Oats Bar (V)'],
                [u'Stone Davis', u'Wednesday', u'Pizza', u'Cheese'],
                [u'Stone Davis', u'Thursday', u'Breakfast', u'Waffle Bar'],
                [u'Stone Davis', u'Thursday', u'Dinner', u'Yellow Squash'],
                [u'Stone Davis', u'Thursday', u'Davis Grille', u'Black Bean Burger'],
                [u'Stone Davis', u'Friday', u'Breakfast', u'Waffle Bar'],
                [u'Stone Davis', u'Friday', u'Dinner', u'Stuffed Tomatoes'],
                [u'Stone Davis', u'Friday', u'Pasta', u'Fra Diavolo'],
                [u'Tower', u'Monday', u'Breakfast', u'Waffle Bar-V'],
                [u'Tower', u'Monday', u'Soup', u'Garlicky Lentil Soup'],
                [u'Tower', u'Monday', u'Fusions', u'Garlic Bread'],
                [u'Tower', u'Tuesday', u'Breakfast', u'Scrambled Eggs-to Order'],
                [u'Tower', u'Tuesday', u'Soup', u'Roast Chicken & Apple Soup'],
                [u'Tower', u'Tuesday', u'Fusions', u'Yellow Rice'],
                [u'Tower', u'Wednesday', u'Breakfast', u'Turkey Sausage Links'],
                [u'Tower', u'Wednesday', u'Pizza/Pasta', u'Cheese, Vegan, Balsamic Veg'],
                [u'Tower', u'Wednesday', u'Fusions', u'Green Coriander & Tamarind Chutney'],
                [u'Tower', u'Thursday', u'Breakfast', u'Scrambled Eggs-to Order'],
                [u'Tower', u'Thursday', u'Pizza/Pasta', u'Cheese, Mac & Chesse, Chick Parm'],
                [u'Tower', u'Thursday', u'Fusions', u'Yellow Onion'],
                [u'Tower', u'Friday', u'Breakfast', u'Turkey Bacon'],
                [u'Tower', u'Friday', u'Soup', u'N.E. Clam Chowder'],
                [u'Tower', u'Friday', u'Composed Salad Bar', u'Caesar Salad-Veg'],
                [u'Tower', u'Saturday', u'Continental Breakfast', u'Fresh Sliced Fruit-V'],
                [u'Tower', u'Saturday', u'Homestyle Dinner', u'Penne Pasta-V'],
                [u'Tower', u'Sunday', u'Brunch', u'Scrambled Egg Whites'],
                [u'Tower', u'Sunday', u'Homestyle Dinner', u'Corn-V'],
                [u'Tower', u'Sunday', u'Pasta', u'Ball Park Hot Dogs'],
                [u'Bae Pao Lu Chow', u'Monday', u'Continental Breakfast', u'Pastries'],
                [u'Bae Pao Lu Chow', u'Wednesday', u'Continental Breakfast', u'Fresh Fruit'],
                [u'Bae Pao Lu Chow', u'Wednesday', u'Pure', u'Cucumber Salad'],
                [u'Bae Pao Lu Chow', u'Wednesday', u'Deli', u'Sliced Ham'],
                [u'Bae Pao Lu Chow', u'Thursday', u'Grill', u'Grilled Chicken'],
                [u'Bae Pao Lu Chow', u'Friday', u'Continental Breakfast', u'Fresh Fruit'],
                [u'Bae Pao Lu Chow', u'Friday', u'Homestyle Dinner', u'Rotisserie Turkey'],
                [u'Bae Pao Lu Chow', u'Saturday', u'Deli MYO', u'Sliced Turkey'],
                [u'Bates', u'Monday', u'Homestyle Lunch', u'Squash & Garlic Pizza'],
                [u'Bates', u'Monday', u'Homestyle Dinner', u'Steamed Carrots'],
                [u'Bates', u'Tuesday', u'Homestyle Lunch', u'Steamed Broccoli'],
                [u'Bates', u'Tuesday', u'Global Grill', u'Basmati Rice'],
                [u'Bates', u'Thursday', u'Homestyle Lunch', u'Green Beans'],
                [u'Bates', u'Thursday', u'Deli', u'Turkey, Ham'],
                [u'Bates', u'Friday', u'Homestyle Dinner', u'Steamed Carrots'],
                [u'Bates', u'Friday', u'Pasta', u'Marinara'],
                [u'Bates', u'Sunday', u'Global Grill', u'Myo Grilled Cheese'],
                [u'Pomeroy', u'Monday', u'Breakfast', u'Assorted Pastry'],
                [u'Pomeroy', u'Monday', u'Lunch', u'Black Bean Burger'],
                [u'Pomeroy', u'Tuesday', u'Breakfast', u'Hard Boiled Eggs'],
                [u'Pomeroy', u'Tuesday', u'Breakfast', u'Cottage Cheese'],
                [u'Pomeroy', u'Tuesday', u'Dinner', u'Garlic Bread'],
                [u'Pomeroy', u'Wednesday', u'Deli', u'Tabbouleh'],
                [u'Pomeroy', u'Thursday', u'Breakfast', u'Hard Boiled Eggs'],
                [u'Pomeroy', u'Thursday', u'Breakfast', u'Leek & Mushroom Quiche'],
                [u'Pomeroy', u'Thursday', u'Deli', u'Potato Salad'],
                [u'Pomeroy', u'Thursday', u'Dinner', u'Roasted Corn'],
                [u'Pomeroy', u'Friday', u'Breakfast', u'Cottage Cheese'],
                [u'Pomeroy', u'Friday', u'Dinner', u'Creamed "Chicken"'],
                [u'Pomeroy', u'Saturday', u'Continental Breakfast', u'Yogurts'],
                [u'Pomeroy', u'Saturday', u'Deli', u'Hummus'],
                [u'Pomeroy', u'Saturday', u'Dinner', u'French Fries'],
                [u'Pomeroy', u'Sunday', u'Deli', u'Cheese of the Day'],
                [u'Pomeroy', u'Sunday', u'Brunch', u'Steamed Corn'],
                [u'Stone Davis', u'Monday', u'Breakfast', u'Steel Cut Oats Bar (V)'],
                [u'Stone Davis', u'Monday', u'Soup', u'Pumpkin Bisque'],
                [u'Stone Davis', u'Tuesday', u'MYO Deli', u'Cheese'],
                [u'Stone Davis', u'Wednesday', u'Soup', u'Tomato'],
                [u'Stone Davis', u'Wednesday', u'Davis Grille', u'Halal Burgers'],
                [u'Stone Davis', u'Thursday', u'Davis Grille', u'Chicken Quesadilla'],
                [u'Stone Davis', u'Friday', u'Breakfast', u'Poached Eggs'],
                [u'Stone Davis', u'Friday', u'Dinner', u'Mashed Sweet Potato'],
                [u'Stone Davis', u'Friday', u'MYO Deli', u'Turkey, Ham,'],
                [u'Tower', u'Monday', u'Breakfast', u'Fresh Sliced Fruit-V'],
                [u'Tower', u'Monday', u'Pizza/Pasta', u'Cheese, Pepperoni, Mushgarlic'],
                [u'Tower', u'Monday', u'Fusions', u'Linguini'],
                [u'Tower', u'Tuesday', u'Breakfast', u'Scrambled Egg Whites-to Order'],
                [u'Tower', u'Tuesday', u'Pizza/Pasta', u'Cheese, Buffalo, Pesto Veg'],
                [u'Tower', u'Tuesday', u'Fusions', u'Black Beans/Pinto Beans'],
                [u'Tower', u'Wednesday', u'Breakfast', u'Scrambled Eggs-to Order'],
                [u'Tower', u'Wednesday', u'Pizza/Pasta', u'Pasta Du Jour'],
                [u'Tower', u'Wednesday', u'Fusions', u'Onion Rings'],
                [u'Tower', u'Thursday', u'Breakfast', u'Scrambled Egg Whites-to Order'],
                [u'Tower', u'Thursday', u'Pizza/Pasta', u'Pasta Du Jour'],
                [u'Tower', u'Thursday', u'Fusions', u'Black Olives'],
                [u'Tower', u'Friday', u'Breakfast', u'Scrambled Eggs-to Order'],
                [u'Tower', u'Friday', u'Soup', u'Pasta Fagiole-Veg'],
                [u'Tower', u'Friday', u'Composed Salad Bar', u'Cucumber Salad-V'],
                [u'Tower', u'Saturday', u'Continental Breakfast', u'Hardboiled Eggs'],
                [u'Tower', u'Saturday', u'Homestyle Dinner', u'Meatballs/Italian Sausage'],
                [u'Tower', u'Sunday', u'Brunch', u'Pancakes'],
                [u'Tower', u'Sunday', u'Soup', u'Black Bean Soup-V'],
                [u'Tower', u'Sunday', u'Pasta', u'Beef Hot Dogs'],
                [u'Bae Pao Lu Chow',
                 u'Monday',
                 u'Continental Breakfast',
                 u'Yogurt & Cottage Cheese'],
                [u'Bae Pao Lu Chow', u'Monday', u'Deli', u'Egg Salad'],
                [u'Bae Pao Lu Chow', u'Tuesday', u'Deli', u'Chicken Salad'],
                [u'Bae Pao Lu Chow',
                 u'Wednesday',
                 u'Pizza',
                 u'Scrod with Olives, Peppers & Onions #1585'],
                [u'Bae Pao Lu Chow', u'Wednesday', u'Deli', u'Platter 18'],
                [u'Bae Pao Lu Chow', u'Thursday', u'Fusion Lunch', u'Blackened Whitefish'],
                [u'Bae Pao Lu Chow', u'Friday', u'Continental Breakfast', u'Oatmeal Bar'],
                [u'Bae Pao Lu Chow', u'Friday', u'Continental Breakfast', u'Pastries'],
                [u'Bae Pao Lu Chow', u'Friday', u'Pure', u'Raw Veggie Burger'],
                [u'Bae Pao Lu Chow', u'Saturday', u'Pizza', u'Bbq Beef Pizza'],
                [u'Bae Pao Lu Chow',
                 u'Sunday',
                 u'Continental Breakfast',
                 u'Hard Boiled Eggs'],
                [u'Bae Pao Lu Chow', u'Sunday', u'Fusion Lunch', u'Pierogies'],
                [u'Bae Pao Lu Chow', u'Sunday', u'Deli MYO', u'Sliced Ham'],
                [u'Bates', u'Monday', u'Homestyle Dinner', u'Macaroni & Cheese'],
                [u'Bates', u'Wednesday', u'Breakfast', u'Steel Cut Oatmeal'],
                [u'Bates', u'Wednesday', u'Deli', u'Ham, Roast Beef'],
                [u'Bates', u'Thursday', u'Homestyle Dinner', u'Steamed Corn'],
                [u'Bates', u'Friday', u'Homestyle Dinner', u'Rice Pilaf'],
                [u'Bates', u'Sunday', u'Brunch Homestyle', u'Vegan Meatballs'],
                [u'Pomeroy', u'Monday', u'Breakfast', u'Egg Whites Upon Request'],
                [u'Pomeroy', u'Monday', u'Pasta Bar', u'Roasted Butternut Squash'],
                [u'Pomeroy', u'Monday', u'Dinner', u'Sweet Potatoes Cakes'],
                [u'Pomeroy', u'Tuesday', u'Breakfast', u'Egg Whites Upon Request'],
                [u'Pomeroy', u'Tuesday', u'Deli', u'Cheese of the Day'],
                [u'Pomeroy', u'Tuesday', u'Dinner', u'Bulgur Pilaf'],
                [u'Pomeroy', u'Wednesday', u'Breakfast', u'Assorted Pastry'],
                [u'Pomeroy', u'Wednesday', u'Lunch', u'South West Rice'],
                [u'Pomeroy', u'Thursday', u'Breakfast', u'Egg Whites Upon Request'],
                [u'Pomeroy', u'Thursday', u'Breakfast', u'Cottage Cheese'],
                [u'Pomeroy', u'Thursday', u'Lunch', u'Garlic Bread'],
                [u'Pomeroy', u'Friday', u'Breakfast', u'Hard Boiled Eggs'],
                [u'Pomeroy', u'Friday', u'Deli', u'Baba Ganoush'],
                [u'Pomeroy', u'Friday', u'Dinner', u'Mashed Potatoes'],
                [u'Pomeroy', u'Saturday', u'Continental Breakfast', u'Sweet Potato Barrels'],
                [u'Pomeroy', u'Saturday', u'Brunch', u'Sausage'],
                [u'Pomeroy', u'Sunday', u'Deli', u'Hummus'],
                [u'Pomeroy', u'Sunday', u'Dinner', u'Garlic Bread'],
                [u'Stone Davis', u'Monday', u'Lunch', u'Black Bean Stew'],
                [u'Stone Davis', u'Monday', u'Davis Grille', u'Halal Burgers'],
                [u'Stone Davis', u'Monday', u'MYO Deli', u'Cheese'],
                [u'Stone Davis', u'Tuesday', u'Lunch', u'Brussel Sprouts'],
                [u'Stone Davis', u'Tuesday', u'Pizza', u'Pepperoni'],
                [u'Stone Davis', u'Wednesday', u'Lunch', u'Swiss Chard'],
                [u'Stone Davis', u'Wednesday', u'Pasta', u'Marinara Sauce'],
                [u'Stone Davis', u'Thursday', u'Breakfast', u'Steel Cut Oats Bar (V)'],
                [u'Stone Davis', u'Thursday', u'Pasta', u'Red Beans'],
                [u'Stone Davis', u'Friday', u'Pizza', u'Apple Pie'],
                [u'Tower', u'Monday', u'Homestyle Lunch', u'Mixed Vegetables'],
                [u'Tower', u'Monday', u'Vegan & Grain Bar', u'Wheat Berry Salad'],
                [u'Tower', u'Monday', u'Deli', u'Turkey, Ham, Roast Beef'],
                [u'Tower', u'Tuesday', u'Homestyle Lunch', u'Carrots-V'],
                [u'Tower', u'Tuesday', u'Vegan & Grain Bar', u'Mediterranean Rice Salad'],
                [u'Tower', u'Tuesday', u'Deli', u'Turkey, Ham, Chicken Salad'],
                [u'Tower', u'Wednesday', u'Homestyle Lunch', u'Fish Tacos'],
                [u'Tower', u'Wednesday', u'Vegan & Grain Bar', u'Potato & Vegetable Curry'],
                [u'Tower', u'Wednesday', u'Deli', u'American, Pepper Jack, Cheddar'],
                [u'Tower', u'Thursday', u'Homestyle Lunch', u'Chili Con Carne'],
                [u'Tower', u'Thursday', u'Vegan & Grain Bar', u'Channa Masala'],
                [u'Tower', u'Thursday', u'Deli', u'American, Muenster, Provolone'],
                [u'Tower', u'Friday', u'Breakfast', u'Fresh Sliced Fruit-V'],
                [u'Tower', u'Friday', u'Pizza/Pasta', u'Alfredo Sauce'],
                [u'Tower', u'Saturday', u'Brunch', u'Scrambled Egg Whites'],
                [u'Tower', u'Saturday', u'Homestyle Dinner', u'Mixed Vegetables-V'],
                [u'Tower', u'Saturday', u'Fusions', u'Closed'],
                [u'Tower', u'Sunday', u'Vegan & Grain Bar', u'Cranberry BBQ Tofu'],
                [u'Tower', u'Sunday', u'Pasta', u'Sauerkraut'],
                [u'Bae Pao Lu Chow', u'Monday', u'Pizza', u'Bacon Turkey Cheddar'],
                [u'Bae Pao Lu Chow', u'Tuesday', u'Pure', u'Raw Hummus'],
                [u'Bae Pao Lu Chow',
                 u'Wednesday',
                 u'Homestyle Dinner',
                 u'Chicken & Broccoli Alfredo'],
                [u'Bae Pao Lu Chow', u'Thursday', u'Fusion Lunch', u'Creole Tofu'],
                [u'Bae Pao Lu Chow',
                 u'Friday',
                 u'Continental Breakfast',
                 u'Yogurt & Cottage Cheese'],
                [u'Bae Pao Lu Chow', u'Friday', u'Pure', u'Gazpacho'],
                [u'Bae Pao Lu Chow', u'Friday', u'Deli', u'Peanut Butter & Jelly'],
                [u'Bae Pao Lu Chow', u'Saturday', u'Pizza', u"Chef's Daily Artisan"],
                [u'Bae Pao Lu Chow', u'Sunday', u'Continental Breakfast', u'Pastries'],
                [u'Bae Pao Lu Chow', u'Sunday', u'Pizza', u'Scones/ Cookies'],
                [u'Bates', u'Monday', u'Global Grill', u'Chicken Fajitas'],
                [u'Bates', u'Monday', u'Deli', u'3 Cheeses-Veg'],
                [u'Bates', u'Friday', u'Breakfast', u'Hardboiled Eggs-Veg'],
                [u'Bates', u'Friday', u'Homestyle Lunch', u'Sauteed Spinach'],
                [u'Bates', u'Friday', u'Deli', u'3 Cheeses-Veg'],
                [u'Bates', u'Saturday', u'Brunch Grill', u'Cinnamon Raisin French Toast'],
                [u'Bates', u'Saturday', u'Pasta', u'Chefs Choice-V'],
                [u'Bates', u'Sunday', u'Brunch Homestyle', u'Garlic Toast'],
                [u'Bates', u'Sunday', u'Deli', u'Chefs Choice'],
                [u'Pomeroy', u'Monday', u'Breakfast', u'Oatmeal Bar'],
                [u'Pomeroy', u'Tuesday', u'Breakfast', u'Waffle Bar'],
                [u'Pomeroy', u'Tuesday', u'Deli', u'Sweet & Spicy Lentils'],
                [u'Pomeroy', u'Wednesday', u'Breakfast', u'Hard Boiled Eggs'],
                [u'Pomeroy', u'Wednesday', u'Breakfast', u'Cottage Cheese'],
                [u'Pomeroy', u'Wednesday', u'Lunch', u'Nacho Chip & Salsa'],
                [u'Pomeroy', u'Thursday', u'Soup of the Day', u'Hot Yogurt & Fava'],
                [u'Pomeroy', u'Friday', u'Breakfast', u'Egg Whites Upon Request'],
                [u'Pomeroy', u'Friday', u'Deli', u'Hummus'],
                [u'Pomeroy', u'Saturday', u'Brunch', u'Pancake'],
                [u'Pomeroy', u'Sunday', u'Continental Breakfast', u'Hard Boiled Eggs'],
                [u'Pomeroy', u'Sunday', u'Brunch', u'Quiche'],
                [u'Stone Davis', u'Monday', u'Breakfast', u'Scrambled Eggs'],
                [u'Stone Davis', u'Monday', u'Lunch', u'Corn'],
                [u'Stone Davis', u'Monday', u'Davis Grille', u'Black Bean Burger'],
                [u'Stone Davis',
                 u'Monday',
                 u'MYO Deli',
                 u'Italian Dress, Black Olives Pepperocini'],
                [u'Stone Davis', u'Tuesday', u'Lunch', u'Roasted Potatoes'],
                [u'Stone Davis', u'Tuesday', u'Davis Grille', u'Halal Burgers'],
                [u'Stone Davis', u'Wednesday', u'Breakfast', u'Egg Whites to Order'],
                [u'Stone Davis', u'Wednesday', u'Lunch', u'Sticky Rice'],
                [u'Stone Davis', u'Wednesday', u'MYO Deli', u'Turkey, Ham, Roast Beef'],
                [u'Stone Davis', u'Thursday', u'Lunch', u'German Bratwurst'],
                [u'Stone Davis', u'Thursday', u'MYO Deli', u'Chicken Salad'],
                [u'Stone Davis', u'Friday', u'Lunch', u'BBQ Pork Butt (Roti)'],
                [u'Stone Davis', u'Friday', u'Pizza', u'Cheese'],
                [u'Tower', u'Monday', u'Breakfast', u'Hard Boiled Eggs'],
                [u'Tower', u'Monday', u'Homestyle Dinner', u'Jerk Chicken'],
                [u'Tower', u'Monday', u'Vegan & Grain Bar', u'Lemon Oregano Chickpeas'],
                [u'Tower', u'Monday', u'Deli', u'Lettuce, Tomato, Onion, Pickles'],
                [u'Tower', u'Tuesday', u'Homestyle Lunch', u'Yellow Squash-V'],
                [u'Tower', u'Tuesday', u'Vegan & Grain Bar', u'Garlicky White Beans'],
                [u'Tower', u'Tuesday', u'Deli', u'Lettuce, Tomato, Onion, Pickles'],
                [u'Tower', u'Wednesday', u'Homestyle Lunch', u'Corn'],
                [u'Tower', u'Wednesday', u'Grill', u'Closed'],
                [u'Tower', u'Wednesday', u'Allergy Station', u'Baked Fish-Lunch'],
                [u'Tower', u'Thursday', u'Homestyle Lunch', u'Broccoli'],
                [u'Tower', u'Thursday', u'Grill', u'"Green Meunster" Melt'],
                [u'Tower', u'Thursday', u'Allergy Station', u'Baked Chicken-Lunch'],
                [u'Tower', u'Friday', u'Homestyle Lunch', u'Roasted Cauliflower'],
                [u'Tower', u'Friday', u'Deli', u'American, Cheddar, Swiss'],
                [u'Tower', u'Saturday', u'Brunch', u'Crunchy French Toast'],
                [u'Tower', u'Saturday', u'Soup', u'Cream of Red Pepper Soup'],
                [u'Tower', u'Saturday', u'Allergy Station', u'Grilled Chicken Breast-Lunch'],
                [u'Tower', u'Sunday', u'Grill', u'Closed'],
                [u'Tower', u'Sunday', u'Deli', u'Closed'],
                [u'Bae Pao Lu Chow', u'Monday', u'Pizza', u"Chef's Daily Artisan"],
                [u'Bae Pao Lu Chow', u'Monday', u'Grill', u'Fresh Cut Fries'],
                [u'Bae Pao Lu Chow', u'Monday', u'Homestyle Dinner', u'Steamed Carrots'],
                [u'Bae Pao Lu Chow', u'Tuesday', u'Continental Breakfast', u'Oatmeal Bar'],
                [u'Bae Pao Lu Chow',
                 u'Tuesday',
                 u'Fusion Lunch',
                 u'Chili Rubbed Pork Medallion'],
                [u'Bae Pao Lu Chow',
                 u'Tuesday',
                 u'Homestyle Dinner',
                 u'Sage/Buttermilk Mashed'],
                [u'Bae Pao Lu Chow', u'Wednesday', u'Continental Breakfast', u'Waffle Bar'],
                [u'Bae Pao Lu Chow', u'Wednesday', u'Grill', u'The Leroy Burger'],
                [u'Bae Pao Lu Chow', u'Wednesday', u'Homestyle Dinner', u'Garlic Crescent'],
                [u'Bae Pao Lu Chow', u'Thursday', u'Continental Breakfast', u'Oatmeal Bar'],
                [u'Bae Pao Lu Chow', u'Thursday', u'Deli', u'Sliced Ham'],
                [u'Bae Pao Lu Chow', u'Saturday', u'Continental Breakfast', u'Oatmeal Bar'],
                [u'Bae Pao Lu Chow', u'Sunday', u'Pizza', u'Cheese Pizza'],
                [u'Bates', u'Monday', u'Breakfast', u'Waffle Station-Veg'],
                [u'Bates', u'Monday', u'Deli', u'Tuna Salad'],
                [u'Bates', u'Tuesday', u'Deli', u'Turkey, Roast Beef'],
                [u'Bates', u'Wednesday', u'Homestyle Dinner', u'Wild Rice'],
                [u'Bates', u'Wednesday', u'Fusion', u'Pork Fried Rice'],
                [u'Bates', u'Thursday', u'Breakfast', u'Hardboiled Eggs-Veg'],
                [u'Bates', u'Thursday', u'Fusion', u'Turkey Ala King'],
                [u'Bates', u'Friday', u'Homestyle Lunch', u'Steamed Green Peas'],
                [u'Bates', u'Friday', u'Global Grill', u'Grilled Cheese'],
                [u'Bates', u'Saturday', u'Brunch Grill', u'Tater Tots'],
                [u'Bates', u'Saturday', u'Deli', u'Chefs Choice'],
                [u'Pomeroy', u'Monday', u'Deli', u'Caprese Salad'],
                [u'Pomeroy', u'Monday', u'Dinner', u'Asparagus & Risotto'],
                [u'Pomeroy', u'Tuesday', u'Breakfast', u'Yukon Potatoes'],
                [u'Pomeroy', u'Tuesday', u'Lunch', u'"Tuna" Casserole'],
                [u'Pomeroy', u'Wednesday', u'Pasta Bar', u'Warm Glass Noodles And'],
                [u'Pomeroy', u'Wednesday', u'Dinner', u'Pp 252'],
                [u'Pomeroy', u'Friday', u'Breakfast', u'Red Bliss Home Fries'],
                [u'Pomeroy', u'Friday', u'Lunch', u'California Blend'],
                [u'Pomeroy', u'Saturday', u'Continental Breakfast', u'Fresh Fruit'],
                [u'Pomeroy', u'Saturday', u'Dinner', u"Pizza '"],
                [u'Pomeroy', u'Sunday', u'Continental Breakfast', u'Yogurts'],
                [u'Pomeroy', u'Sunday', u'Brunch', u'Steamed Rice'],
                [u'Stone Davis', u'Monday', u'Breakfast', u'Classic French Toast'],
                [u'Stone Davis', u'Monday', u'Dinner', u'Poultry Seasoned Tofu'],
                [u'Stone Davis', u'Monday', u'Davis Grille', u'White Bean & Pepper'],
                [u'Stone Davis', u'Tuesday', u'Breakfast', u'Egg Whites to Order'],
                [u'Stone Davis', u'Tuesday', u'Dinner', u'Bok Choy'],
                [u'Stone Davis', u'Tuesday', u'Davis Grille', u'Roasted Red & Provolone'],
                [u'Stone Davis', u'Wednesday', u'Breakfast', u'3 Cheese Omelets'],
                [u'Stone Davis', u'Wednesday', u'Dinner', u'Veggie Lasagna'],
                [u'Stone Davis', u'Wednesday', u'MYO Deli', u'Hummus Wrap'],
                [u'Stone Davis', u'Thursday', u'Lunch', u'Turnips'],
                [u'Stone Davis', u'Thursday', u'Pizza', u'White'],
                [u'Stone Davis', u'Thursday', u'MYO Deli', u'Cranberry Sauce'],
                [u'Stone Davis', u'Friday', u'Lunch', u'Creamed Spinach'],
                [u'Tower', u'Monday', u'Breakfast', u'Cheese Omelets'],
                [u'Tower', u'Monday', u'Composed Salad Bar', u'Caesar Salad-Veg'],
                [u'Tower', u'Tuesday', u'Breakfast', u'Cream of Wheat-V'],
                [u'Tower', u'Tuesday', u'Composed Salad Bar', u'House Salad-V'],
                [u'Tower', u'Wednesday', u'Breakfast', u'Hard Boiled Eggs'],
                [u'Tower', u'Wednesday', u'Homestyle Dinner', u'Collard Greens-V'],
                [u'Tower', u'Wednesday', u'Composed Salad Bar', u'Green Bean Salad-V'],
                [u'Tower', u'Thursday', u'Breakfast', u'Grits-V'],
                [u'Tower', u'Thursday', u'Homestyle Dinner', u'Chocolate Chip Pancakes'],
                [u'Tower', u'Thursday', u'Composed Salad Bar', u'Potato Salad-Veg'],
                [u'Tower', u'Friday', u'Breakfast', u'Hard Boiled Eggs'],
                [u'Tower', u'Friday', u'Allergy Station', u'G.F. Crab Cake-Lunch'],
                [u'Tower', u'Saturday', u'Brunch', u'Chicken Tenders'],
                [u'Tower', u'Saturday', u'Grill', u'Closed'],
                [u'Tower', u'Sunday', u'Continental Breakfast', u'Fresh Sliced Fruit-V'],
                [u'Tower', u'Sunday', u'Homestyle Dinner', u'Stuffed Shells-Veg'],
                [u'Bae Pao Lu Chow', u'Monday', u'Grill', u'Vegan Crab Cake'],
                [u'Bae Pao Lu Chow', u'Tuesday', u'Grill', u'Fried Wontons'],
                [u'Bae Pao Lu Chow',
                 u'Wednesday',
                 u'Continental Breakfast',
                 u'Yogurt & Cottage Cheese'],
                [u'Bae Pao Lu Chow',
                 u'Wednesday',
                 u'Fusion Lunch',
                 u'Garden Style Primavera Pasta'],
                [u'Bae Pao Lu Chow', u'Thursday', u'Pure', u'Crunchy Taco'],
                [u'Bae Pao Lu Chow', u'Thursday', u'Homestyle Dinner', u'Gravy'],
                [u'Bae Pao Lu Chow', u'Friday', u'Grill', u'Beef Salisbury'],
                [u'Bae Pao Lu Chow', u'Friday', u'Homestyle Dinner', u'Traditional Stuffing'],
                [u'Bae Pao Lu Chow', u'Friday', u'Deli', u'Pepperoni'],
                [u'Bae Pao Lu Chow',
                 u'Saturday',
                 u'Continental Breakfast',
                 u'Yogurt & Cottage Cheese'],
                [u'Bae Pao Lu Chow', u'Saturday', u'Fusion Lunch', u'Niman Sausage'],
                [u'Bae Pao Lu Chow', u'Sunday', u'Continental Breakfast', u'Waffle Bar'],
                [u'Bae Pao Lu Chow', u'Sunday', u'Homestyle Dinner', u'Lima Beans'],
                [u'Bates', u'Tuesday', u'Breakfast', u'Scrambled Eggs Or Whites-Veg'],
                [u'Bates', u'Wednesday', u'Breakfast', u'Scrambled Eggs Or Whites-Veg'],
                [u'Bates', u'Wednesday', u'Homestyle Dinner', u'Chicken Divan'],
                [u'Bates', u'Wednesday', u'Global Grill', u'Kettle Chips'],
                [u'Bates', u'Thursday', u'Homestyle Dinner', u'Beef Ribs'],
                [u'Bates', u'Saturday', u'Continental Breakfast', u'Waffle Station-Veg'],
                [u'Bates', u'Sunday', u'Continental Breakfast', u'Steel Cut Oatmeal'],
                [u'Bates', u'Sunday', u'Pasta', u'Marinara-V'],
                [u'Pomeroy', u'Monday', u'Breakfast', u'Hard Boiled Eggs'],
                [u'Pomeroy', u'Monday', u'Breakfast', u'Cottage Cheese'],
                [u'Pomeroy', u'Monday', u'Lunch', u'Roasted Corn'],
                [u'Pomeroy', u'Tuesday', u'Breakfast', u'Scrambled Eggs'],
                [u'Pomeroy', u'Tuesday', u'Pasta Bar', u'Spaghetti Squash with Garlic'],
                [u'Pomeroy', u'Wednesday', u'Lunch', u'Tamale'],
                [u'Pomeroy', u'Thursday', u'Breakfast', u'Assorted Pastry'],
                [u'Pomeroy', u'Thursday', u'Deli', u'Hummus'],
                [u'Pomeroy', u'Thursday', u'Dinner', u'Roasted Mushroom Gravy'],
                [u'Pomeroy', u'Friday', u'Deli', u'Cheese of the Day'],
                [u'Pomeroy', u'Friday', u'Dinner', u'Green Beans'],
                [u'Pomeroy', u'Saturday', u'Continental Breakfast', u'Cottage Cheese'],
                [u'Pomeroy', u'Saturday', u'Brunch', u'Chicken Pie'],
                [u'Pomeroy', u'Sunday', u'Continental Breakfast', u'Belgian Waffle Bar'],
                [u'Pomeroy', u'Sunday', u'Deli', u'Tofu Hummus'],
                [u'Stone Davis', u'Monday', u'Lunch', u'Tamale Pie'],
                [u'Stone Davis', u'Monday', u'Pizza', u'Supreme'],
                [u'Stone Davis', u'Tuesday', u'Lunch', u'Italian Pot Roast'],
                [u'Stone Davis', u'Tuesday', u'MYO Deli', u'Southwest Turkey'],
                [u'Stone Davis', u'Wednesday', u'Lunch', u'Miso Glazed Salmon'],
                [u'Stone Davis', u'Wednesday', u'Davis Grille', u'All American Burger'],
                [u'Stone Davis', u'Thursday', u'Breakfast', u'Sweet Potato Tots'],
                [u'Stone Davis', u'Thursday', u'Dinner', u'Wild Rice'],
                [u'Stone Davis',
                 u'Thursday',
                 u'Davis Grille',
                 u'Monte Cristo with Marmalade'],
                [u'Stone Davis', u'Friday', u'Breakfast', u'Hollandaise'],
                [u'Stone Davis', u'Friday', u'MYO Deli', u'Cheese'],
                [u'Tower', u'Monday', u'Homestyle Lunch', u'Succotash'],
                [u'Tower', u'Monday', u'Pizza/Pasta', u'Marinara Sauce-V'],
                [u'Tower', u'Monday', u'Fusions', u'Tomatoes'],
                [u'Tower', u'Tuesday', u'Breakfast', u'Fresh Sliced Fruit-V'],
                [u'Tower', u'Tuesday', u'Pizza/Pasta', u'Marinara Sauce'],
                [u'Tower', u'Tuesday', u'Fusions', u'Salsa'],
                [u'Tower', u'Wednesday', u'Breakfast', u'Waffle Bar-V'],
                [u'Tower', u'Wednesday', u'Pizza/Pasta', u'Basil Pesto'],
                [u'Tower', u'Wednesday', u'Fusions', u'Saffron Rice'],
                [u'Tower', u'Thursday', u'Pizza/Pasta', u'Bolognese Sauce'],
                [u'Tower', u'Thursday', u'Fusions', u'Roasted Red Peppers'],
                [u'Tower', u'Friday', u'Pizza/Pasta', u'Pasta Du Jour'],
                [u'Tower', u'Friday', u'Fusions', u'Closed'],
                [u'Tower',
                 u'Saturday',
                 u'Continental Breakfast',
                 u'Assorted Breakfast Pastry-Veg'],
                [u'Tower', u'Saturday', u'Homestyle Dinner', u'Vegan Meatballs-V'],
                [u'Tower', u'Sunday', u'Brunch', u'Turkey Sausage Links'],
                [u'Tower', u'Sunday', u'Pizza', u'Closed'],
                [u'Tower', u'Sunday', u'Pasta', u'Cheese Sauce'],
                [u'Bae Pao Lu Chow', u'Monday', u'Pure', u'Tomato Sauce'],
                [u'Bae Pao Lu Chow', u'Monday', u'Deli', u'Sliced Turkey'],
                [u'Bae Pao Lu Chow', u'Tuesday', u'Fusion Lunch', u'Field Greens'],
                [u'Bae Pao Lu Chow', u'Tuesday', u'Homestyle Dinner', u'Broccoli'],
                [u'Bae Pao Lu Chow', u'Wednesday', u'Continental Breakfast', u'Oatmeal Bar'],
                [u'Bae Pao Lu Chow', u'Thursday', u'Grill', u'Grilled Caesar Salad'],
                [u'Bae Pao Lu Chow',
                 u'Thursday',
                 u'Homestyle Dinner',
                 u'Carved Roast Beef (Ro)'],
                [u'Bae Pao Lu Chow', u'Friday', u'Fusion Lunch', u'Manicotti'],
                [u'Bae Pao Lu Chow',
                 u'Saturday',
                 u'Continental Breakfast',
                 u'Hard Boiled Eggs'],
                [u'Bae Pao Lu Chow', u'Saturday', u'Grill', u'Tator Barrels/ Chips'],
                [u'Bae Pao Lu Chow', u'Sunday', u'Pizza', u'Pepperoni Pizza'],
                [u'Bates', u'Monday', u'Homestyle Dinner', u'Collard Greens'],
                [u'Bates', u'Tuesday', u'Breakfast', u'Steel Cut Oatmeal'],
                [u'Bates', u'Wednesday', u'Homestyle Lunch', u'Creole Tofu'],
                [u'Bates', u'Thursday', u'Breakfast', u'Waffle Station-Veg'],
                [u'Bates', u'Thursday', u'Homestyle Dinner', u'Creamed Spinach'],
                [u'Bates', u'Saturday', u'Continental Breakfast', u'Hardboiled Eggs-Veg'],
                [u'Bates', u'Saturday', u'Homestyle Dinner', u'Roasted Chicken'],
                [u'Bates', u'Saturday', u'Deli', u'Chefs Choice'],
                [u'Bates', u'Sunday', u'Homestyle Dinner', u'Pork Sheppards Pie'],
                [u'Pomeroy', u'Monday', u'Breakfast', u'Maple Glazed Tofu'],
                [u'Pomeroy', u'Monday', u'Deli', u'Bean Curd with Chili Sauce'],
                [u'Pomeroy', u'Monday', u'Dinner', u'Green Beans'],
                [u'Pomeroy', u'Tuesday', u'Breakfast', u'Chocolate Chip Pancakes'],
                [u'Pomeroy', u'Tuesday', u'Lunch', u'Yellow Rice'],
                [u'Pomeroy', u'Wednesday', u'Breakfast', u'Waffle Bar'],
                [u'Pomeroy', u'Wednesday', u'Pasta Bar', u'198'],
                [u'Pomeroy', u'Wednesday', u'Dinner', u'Coconut Rice with Sambal & Okra'],
                [u'Pomeroy', u'Thursday', u'Breakfast', u'Lyonnais Potatoes'],
                [u'Pomeroy', u'Thursday', u'Pasta Bar', u'Butternut Squash Over'],
                [u'Pomeroy', u'Thursday', u'Dinner', u'Mashed Potatoes'],
                [u'Pomeroy', u'Friday', u'Breakfast', u'Buttermilk Pancakes'],
                [u'Pomeroy', u'Saturday', u'Continental Breakfast', u'Oatmeal Bar'],
                [u'Pomeroy', u'Saturday', u'Deli', u'Cheese of the Day'],
                [u'Pomeroy', u'Sunday', u'Continental Breakfast', u'Yukon Potatoes'],
                [u'Pomeroy',
                 u'Sunday',
                 u'Dinner',
                 u'Roasted Parsnip & Sweet Potatoes with Caper Vinaigrette'],
                [u'Stone Davis', u'Monday', u'Dinner', u'Lemon Spinach'],
                [u'Stone Davis', u'Monday', u'Pasta', u'Marinara Sauce'],
                [u'Stone Davis', u'Tuesday', u'Breakfast', u'Buttermilk Pancakes'],
                [u'Stone Davis', u'Tuesday', u'Pasta', u'Marinara Sauce'],
                [u'Stone Davis', u'Wednesday', u'Dinner', u'Green Beans'],
                [u'Stone Davis', u'Thursday', u'Breakfast', u'Scrambled Eggs'],
                [u'Stone Davis', u'Thursday', u'Dinner', u'Chicken Gumbo'],
                [u'Stone Davis', u'Friday', u'Breakfast', u'Hard Boiled Eggs'],
                [u'Stone Davis', u'Friday', u'Dinner', u'Meatloaf'],
                [u'Stone Davis', u'Friday', u'Davis Grille', u'Fried Plantains'],
                [u'Tower', u'Monday', u'Breakfast', u'Turkey Sausage Patties'],
                [u'Tower', u'Monday', u'Homestyle Dinner', u'Baked Sweet Potatoes'],
                [u'Tower', u'Monday', u'Composed Salad Bar', u'Cous Cous Salad-V'],
                [u'Tower', u'Tuesday', u'Breakfast', u'Brsug/Cinn Pumpkin Pancakes'],
                [u'Tower', u'Tuesday', u'Homestyle Dinner', u'String Beans'],
                [u'Tower', u'Tuesday', u'Composed Salad Bar', u'Lentil Salad-V'],
                [u'Tower', u'Wednesday', u'Breakfast', u'Egg & Cheese Muffin'],
                [u'Tower', u'Wednesday', u'Homestyle Dinner', u'Red Beans & Rice'],
                [u'Tower', u'Wednesday', u'Fusions', u'Chicken Tikka'],
                [u'Tower', u'Thursday', u'Breakfast', u'French Toast'],
                [u'Tower', u'Thursday', u'Homestyle Dinner', u'Red Bliss Home Fries-V'],
                [u'Tower', u'Thursday', u'Fusions', u'Mediterranean Pasts'],
                [u'Tower', u'Friday', u'Breakfast', u'Egg & Cheese Muffin'],
                [u'Tower', u'Friday', u'Homestyle Dinner', u'Kim Chee'],
                [u'Tower', u'Friday', u'Allergy Station', u'Baked Chicken Parm-Dinner'],
                [u'Tower', u'Saturday', u'Pasta', u'Garlic Butter Sauce-Veg'],
                [u'Tower', u'Sunday', u'Continental Breakfast', u'Steel Cut Oatmeal-V'],
                [u'Tower', u'Sunday', u'Homestyle Dinner', u'Stuffing-Veg'],
                [u'Bae Pao Lu Chow', u'Monday', u'Fusion Lunch', u'Turkey Ala King'],
                [u'Bae Pao Lu Chow', u'Tuesday', u'Grill', u'Teriyaki Tofu/Chicken'],
                [u'Bae Pao Lu Chow',
                 u'Tuesday',
                 u'Homestyle Dinner',
                 u'Roasted Yellow Beets'],
                [u'Bae Pao Lu Chow',
                 u'Wednesday',
                 u'Continental Breakfast',
                 u'Hard Boiled Eggs'],
                [u'Bae Pao Lu Chow',
                 u'Wednesday',
                 u'Grill',
                 u'Ratatouille Topped Veggie Burger'],
                [u'Bae Pao Lu Chow', u'Wednesday', u'Deli', u'Sliced Turkey'],
                [u'Bae Pao Lu Chow', u'Thursday', u'Grill', u'Southwest Grilled Tofu'],
                [u'Bae Pao Lu Chow',
                 u'Thursday',
                 u'Homestyle Dinner',
                 u'Basil Whipped Potatoes'],
                [u'Bae Pao Lu Chow', u'Thursday', u'Deli', u'Egg Salad'],
                [u'Bae Pao Lu Chow', u'Friday', u'Soup', u'Ginger Soup'],
                [u'Bae Pao Lu Chow',
                 u'Saturday',
                 u'Homestyle Dinner',
                 u'Yellow Squash W Red Pepper'],
                [u'Bae Pao Lu Chow', u'Sunday', u'Homestyle Dinner', u'Tempeh Chili'],
                [u'Bates', u'Monday', u'Global Grill', u'Tortilla Chips'],
                [u'Bates', u'Wednesday', u'Homestyle Lunch', u'Okra & Tomato'],
                [u'Bates', u'Wednesday', u'Global Grill', u'International Burger Bar'],
                [u'Bates', u'Thursday', u'Breakfast', u'Steel Cut Oatmeal'],
                [u'Bates', u'Thursday', u'Global Grill', u'Grilled Keilbasa'],
                [u'Bates', u'Thursday', u'Fusion', u'Vegetarian Ala King'],
                [u'Bates', u'Friday', u'Homestyle Lunch', u'Garlic Bread Sticks'],
                [u'Bates', u'Friday', u'Global Grill', u'French Fries'],
                [u'Bates', u'Saturday', u'Homestyle Dinner', u'Eggplant Parmesan'],
                [u'Bates', u'Sunday', u'Continental Breakfast', u'Hardboiled Eggs-Veg'],
                [u'Bates', u'Sunday', u'Homestyle Dinner', u'Vegan Pot Pie'],
                [u'Pomeroy', u'Monday', u'Breakfast', u'Fried Egg Sandwich'],
                [u'Pomeroy', u'Monday', u'Deli', u'Tabbouleh'],
                [u'Pomeroy', u'Tuesday', u'Breakfast', u'Fresh Fruit'],
                [u'Pomeroy', u'Tuesday', u'Lunch', u'Roasted Winter Vegetable'],
                [u'Pomeroy', u'Wednesday', u'Breakfast', u'Oatmeal Bar'],
                [u'Pomeroy', u'Wednesday', u'Deli', u'Cheese of the Day'],
                [u'Pomeroy',
                 u'Wednesday',
                 u'Dinner',
                 u'Castelluccio Lentils with Tomatoes And'],
                [u'Pomeroy', u'Thursday', u'Pasta Bar', u'Penne & Brown Butter Sauce'],
                [u'Pomeroy', u'Friday', u'Breakfast', u'Fresh Fruit'],
                [u'Pomeroy', u'Friday', u'Lunch', u'Grilled Caprese Sandwich'],
                [u'Pomeroy', u'Saturday', u'Continental Breakfast', u'Hard Boiled Eggs'],
                [u'Pomeroy', u'Saturday', u'Deli', u'Guacamole'],
                [u'Pomeroy', u'Saturday', u'Dinner', u'Roasted Vegetable'],
                [u'Pomeroy', u'Sunday', u'Soup of the Day', u'Rice Soup'],
                [u'Pomeroy', u'Sunday', u'Brunch', u'"Bacon"'],
                [u'Pomeroy', u'Sunday', u'Dessert', u'Ice Cream Sundae Bar'],
                [u'Stone Davis', u'Monday', u'Dinner', u'Mashed Potatoes'],
                [u'Stone Davis', u'Monday', u'Pasta', u'Putanesca'],
                [u'Stone Davis', u'Tuesday', u'Breakfast', u'Tater Tots'],
                [u'Stone Davis', u'Tuesday', u'Dinner', u'Sesame Tofu'],
                [u'Stone Davis', u'Tuesday', u'Pasta', u'Primavera'],
                [u'Stone Davis', u'Thursday', u'Breakfast', u'Egg Whites to Order'],
                [u'Stone Davis', u'Thursday', u'Dinner', u'White Bean Quiche'],
                [u'Stone Davis', u'Friday', u'Breakfast', u'Scrambled Eggs'],
                [u'Stone Davis', u'Friday', u'Dinner', u'Veggie Risotto'],
                [u'Tower', u'Monday', u'Breakfast', u'Scrambled Eggs-to Order'],
                [u'Tower', u'Monday', u'Fusions', u'Steamers'],
                [u'Tower', u'Tuesday', u'Breakfast', u'Seasoned Sliced Potatoes-V'],
                [u'Tower', u'Tuesday', u'Homestyle Dinner', u'Broken Rice'],
                [u'Tower', u'Tuesday', u'Fusions', u'Fried Rice'],
                [u'Tower', u'Wednesday', u'Breakfast', u'Scrambled Eggs'],
                [u'Tower', u'Wednesday', u'Soup', u'Beef Chili'],
                [u'Tower', u'Wednesday', u'Fusions', u'Marinated Chicken Breast'],
                [u'Tower', u'Thursday', u'Breakfast', u'Red Bliss Home Fries-V'],
                [u'Tower', u'Thursday', u'Soup', u'Chicken & Rice Soup'],
                [u'Tower', u'Thursday', u'Fusions', u'Whole Grain Rotini'],
                [u'Tower', u'Friday', u'Breakfast', u'Ham & Swiss Omelet'],
                [u'Tower', u'Friday', u'Homestyle Dinner', u'Steamed Edamame'],
                [u'Tower', u'Friday', u'Grill', u'Beef Hot Dogs'],
                [u'Tower', u'Saturday', u'Brunch', u'Yellow Corn-V'],
                [u'Tower', u'Saturday', u'Pasta', u'Pasta Du Jour'],
                [u'Tower',
                 u'Sunday',
                 u'Continental Breakfast',
                 u'Assorted Breakfast Pastry-Veg'],
                [u'Tower', u'Sunday', u'Homestyle Dinner', u'Turkey Gravy'],
                [u'Tower', u'Sunday', u'Pasta', u'Alfredo Sauce-V'],
                [u'Bae Pao Lu Chow', u'Monday', u'Fusion Lunch', u'Roasted Sweet Pots'],
                [u'Bae Pao Lu Chow', u'Monday', u'Deli', u'Sliced Ham'],
                [u'Bae Pao Lu Chow', u'Tuesday', u'Continental Breakfast', u'Fresh Fruit'],
                [u'Bae Pao Lu Chow', u'Tuesday', u'Deli', u'Sliced Turkey'],
                [u'Bae Pao Lu Chow', u'Wednesday', u'Grill', u'Fresh Cut Fries'],
                [u'Bae Pao Lu Chow',
                 u'Thursday',
                 u'Continental Breakfast',
                 u'Hard Boiled Eggs'],
                [u'Bae Pao Lu Chow',
                 u'Thursday',
                 u'Continental Breakfast',
                 u'Yogurt & Cottage Cheese'],
                [u'Bae Pao Lu Chow', u'Friday', u'Pizza', u'Chicken Parm. Pizza'],
                [u'Bae Pao Lu Chow', u'Sunday', u'Grill', u'Tater Triangles'],
                [u'Bates', u'Monday', u'Homestyle Lunch', u'Thai Shrimp Pizza'],
                [u'Bates', u'Monday', u'Pasta', u'Alfredo'],
                [u'Bates', u'Monday', u'Fusion', u'Pecans/Goat Cheese'],
                [u'Bates', u'Tuesday', u'Global Grill', u'Chicken Curry'],
                [u'Bates', u'Tuesday', u'Deli', u'3 Cheeses-Veg'],
                [u'Bates', u'Wednesday', u'Global Grill', u'Black Bean Burgers'],
                [u'Bates', u'Thursday', u'Homestyle Lunch', u'Baked Chicken Bruschetta'],
                [u'Bates', u'Thursday', u'Pasta', u'Pesto'],
                [u'Bates', u'Friday', u'Breakfast', u'Waffle Station-Veg'],
                [u'Bates',
                 u'Saturday',
                 u'Continental Breakfast',
                 u'Scrambled Eggs Or Whites-Veg'],
                [u'Bates', u'Sunday', u'Homestyle Dinner', u'Steamed Cauliflower'],
                [u'Pomeroy', u'Monday', u'Breakfast', u'Fresh Fruit'],
                [u'Pomeroy', u'Monday', u'Deli', u'Hummus'],
                [u'Pomeroy', u'Monday', u'Dinner', u'Tuscan White Beans'],
                [u'Pomeroy', u'Tuesday', u'Breakfast', u'Assorted Pastry'],
                [u'Pomeroy', u'Tuesday', u'Lunch', u'Lima Beans'],
                [u'Pomeroy', u'Wednesday', u'Breakfast', u'Potato Barrels'],
                [u'Pomeroy', u'Wednesday', u'Deli', u'Coleslaw'],
                [u'Pomeroy', u'Wednesday', u'Dinner', u'Goat Cheese'],
                [u'Pomeroy', u'Thursday', u'Deli', u'Cheese of the Day'],
                [u'Pomeroy', u'Thursday', u'Dinner', u'Peas'],
                [u'Pomeroy', u'Friday', u'Breakfast', u'Assorted Pastry'],
                [u'Pomeroy',
                 u'Saturday',
                 u'Continental Breakfast',
                 u'Assorted Breakfast Pastry'],
                [u'Pomeroy', u'Saturday', u'Deli', u'Nacho Display'],
                [u'Pomeroy', u'Saturday', u'Dinner', u'Cheese Pizza'],
                [u'Pomeroy', u'Sunday', u'Pasta Bar @ Dinner', u'Pasta with Marinara Sauce'],
                [u'Stone Davis', u'Monday', u'Breakfast', u'Hash Browns'],
                [u'Stone Davis', u'Monday', u'Soup', u'Tomato & Chickpea'],
                [u'Stone Davis', u'Monday', u'MYO Deli', u'Salami, Ham, Pepperoni'],
                [u'Stone Davis', u'Tuesday', u'Breakfast', u'Pork Bacon'],
                [u'Stone Davis', u'Tuesday', u'Soup', u'Lentil'],
                [u'Stone Davis', u'Wednesday', u'Breakfast', u'Pork Sausage Patty'],
                [u'Stone Davis', u'Wednesday', u'Dinner', u'Garlic Bread'],
                [u'Stone Davis', u'Thursday', u'Davis Grille', u'Halal Burgers'],
                [u'Stone Davis', u'Friday', u'Breakfast', u'Egg Whites to Order'],
                [u'Stone Davis', u'Friday', u'Dinner', u'Carrots'],
                [u'Stone Davis', u'Friday', u'Pasta', u'Marinara Sauce'],
                [u'Tower', u'Monday', u'Breakfast', u'Scrambled Egg Whites-to Order'],
                [u'Tower', u'Monday', u'Soup', u'Curried Chicken Soup'],
                [u'Tower', u'Monday', u'Fusions', u'Clams'],
                [u'Tower', u'Tuesday', u'Breakfast', u'Pork Bacon'],
                [u'Tower', u'Tuesday', u'Soup', u'Pumpkin Bisque'],
                [u'Tower', u'Tuesday', u'Fusions', u'Seasoned Chicken'],
                [u'Tower', u'Wednesday', u'Breakfast', u'Shredded Hashbrowns-V'],
                [u'Tower', u'Wednesday', u'Soup', u'Mushroom, Celery, & Garlic Soup'],
                [u'Tower', u'Wednesday', u'Fusions', u'Clarified Butter'],
                [u'Tower', u'Thursday', u'Breakfast', u'Corned Beef Hash'],
                [u'Tower', u'Thursday', u'Soup', u'Cream of Tomato Soup-V'],
                [u'Tower', u'Thursday', u'Fusions', u'Sauteed Spinach'],
                [u'Tower', u'Friday', u'Breakfast', u'Seasoned Sliced Potatoes-V'],
                [u'Tower', u'Friday', u'Homestyle Dinner', u'Flour Tortillas'],
                [u'Tower', u'Friday', u'Grill', u'French Fries'],
                [u'Tower', u'Saturday', u'Continental Breakfast', u'Waffle Bar-V'],
                [u'Tower', u'Saturday', u'Brunch', u'Macaroni & Cheese-Veg'],
                [u'Tower', u'Sunday', u'Brunch', u'Scrambled Eggs'],
                [u'Tower', u'Sunday', u'Homestyle Dinner', u'Green Beans-V'],
                [u'Tower', u'Sunday', u'Pasta', u'Pasta Du Jour'],
                [u'Bae Pao Lu Chow',
                 u'Monday',
                 u'Homestyle Dinner',
                 u'Tuscan Rotisserie Chicken 3127'],
                [u'Bae Pao Lu Chow', u'Monday', u'Deli', u'Salami'],
                [u'Bae Pao Lu Chow', u'Tuesday', u'Continental Breakfast', u'Pastries'],
                [u'Bae Pao Lu Chow', u'Tuesday', u'Fusion Lunch', u'Cranberries, Pecans'],
                [u'Bae Pao Lu Chow', u'Wednesday', u'Continental Breakfast', u'Pastries'],
                [u'Bae Pao Lu Chow',
                 u'Wednesday',
                 u'Fusion Lunch',
                 u'Spinach, Bacon & Parmesan Pasta'],
                [u'Bae Pao Lu Chow', u'Wednesday', u'Deli', u'Pastrami'],
                [u'Bae Pao Lu Chow', u'Thursday', u'Soup', u'Beef & Rice'],
                [u'Bae Pao Lu Chow', u'Thursday', u'Deli', u'Buffalo Chicken Wrap'],
                [u'Bae Pao Lu Chow', u'Friday', u'Pizza', u"Chef's Daily Artisan"],
                [u'Bae Pao Lu Chow', u'Saturday', u'Continental Breakfast', u'Pastries'],
                [u'Bae Pao Lu Chow', u'Saturday', u'Fusion Lunch', u'Vegetable Frittata'],
                [u'Bae Pao Lu Chow', u'Saturday', u'Deli MYO', u'Sliced Ham'],
                [u'Bae Pao Lu Chow', u'Sunday', u'Fusion Lunch', u'Scrambled Eggs'],
                [u'Bates', u'Monday', u'Deli', u'Turkey, Ham'],
                [u'Bates', u'Tuesday', u'Homestyle Lunch', u'Bok Choy'],
                [u'Bates', u'Wednesday', u'Breakfast', u'Hardboiled Eggs-Veg'],
                [u'Bates', u'Wednesday', u'Homestyle Lunch', u'Corn on the Cobb'],
                [u'Bates', u'Thursday', u'Homestyle Lunch', u'Garlic Toast'],
                [u'Bates', u'Thursday', u'Homestyle Dinner', u'Baked Potato Bar'],
                [u'Bates', u'Friday', u'Fusion', u'Breakfast Scramble'],
                [u'Bates', u'Saturday', u'Homestyle Dinner', u'Baked Sweet Potatoes'],
                [u'Bates', u'Sunday', u'Continental Breakfast', u'Waffle Station-Veg'],
                [u'Bates', u'Sunday', u'Pasta', u'Chefs Choice-V'],
                [u'Pomeroy', u'Monday', u'Breakfast', u'Yogurts'],
                [u'Pomeroy', u'Monday', u'Lunch', u'Fresh French Fries'],
                [u'Pomeroy', u'Tuesday', u'Soup of the Day', u'Cream of Mushroom'],
                [u'Pomeroy', u'Tuesday', u'Dinner', u'Ratatouille'],
                [u'Pomeroy', u'Wednesday', u'Breakfast', u'Veggie Bacon'],
                [u'Pomeroy', u'Wednesday', u'Deli', u'Hummus'],
                [u'Pomeroy', u'Thursday', u'Breakfast', u'Scrambled Eggs'],
                [u'Pomeroy', u'Thursday', u'Breakfast', u'Fresh Fruit'],
                [u'Pomeroy', u'Thursday', u'Deli', u'Tabbouleh'],
                [u'Pomeroy', u'Friday', u'Pasta Bar', u'Chicken & Broccoli'],
                [u'Pomeroy', u'Friday', u'Dinner', u'Stuffing'],
                [u'Pomeroy', u'Saturday', u'Brunch', u'Scramble Eggs'],
                [u'Pomeroy', u'Saturday', u'Dinner', u'Corn'],
                [u'Pomeroy', u'Sunday', u'Deli', u'Olives'],
                [u'Pomeroy', u'Sunday', u'Dinner', u'Eggplant Parmesan'],
                [u'Stone Davis', u'Monday', u'Breakfast', u'Egg & Cheese on English Muffin (Veg)'],
                [u'Stone Davis', u'Monday', u'Pizza', u'Pierogi'],
                [u'Stone Davis', u'Tuesday', u'Breakfast', u'Egg & Cheese on Bagel (Veg)'],
                [u'Stone Davis', u'Tuesday', u'Soup', u'Pasta Fagioli'],
                [u'Stone Davis', u'Tuesday', u'MYO Deli', u'Chipotle Mayo'],
                [u'Stone Davis',
                 u'Wednesday',
                 u'Breakfast',
                 u'Bacon Egg & Cheese Biscuit (Veg)'],
                [u'Stone Davis', u'Wednesday', u'Soup', u'Italian Wedding'],
                [u'Stone Davis', u'Wednesday', u'Davis Grille', u'Black Bean Burger'],
                [u'Stone Davis', u'Thursday', u'Breakfast', u'Crunchy French Toast'],
                [u'Stone Davis', u'Thursday', u'Dinner', u'Snap Peas'],
                [u'Stone Davis', u'Friday', u'Breakfast', u'Pit Ham'],
                [u'Stone Davis', u'Friday', u'Soup', u'Split Pea'],
                [u'Stone Davis', u'Friday', u'MYO Deli', u'Roasted Pepper Tuna Salad'],
                [u'Tower', u'Monday', u'Homestyle Lunch', u'Beef Burgundy'],
                [u'Tower', u'Monday', u'Pizza/Pasta', u'Pasta Du Jour'],
                [u'Tower', u'Monday', u'Fusions', u'Vegetable Broth'],
                [u'Tower', u'Tuesday', u'Breakfast', u'Waffle Bar-V'],
                [u'Tower', u'Tuesday', u'Pizza/Pasta', u'Pasta Du Jour'],
                [u'Tower', u'Tuesday', u'Fusions', u'Sour Cream'],
                [u'Tower', u'Wednesday', u'Breakfast', u'Scrambled Egg Whites-to Order'],
                [u'Tower', u'Wednesday', u'Pizza/Pasta', u'Marinara Sauce'],
                [u'Tower', u'Wednesday', u'Fusions', u'Lemons'],
                [u'Tower', u'Thursday', u'Breakfast', u'Waffle Bar-V'],
                [u'Tower', u'Thursday', u'Pizza/Pasta', u'Marinara Sauce'],
                [u'Tower', u'Thursday', u'Fusions', u'Feta Cheese'],
                [u'Tower', u'Friday', u'Breakfast', u'Scrambled Egg Whites-to Order'],
                [u'Tower', u'Friday', u'Pizza/Pasta', u'Cheese, Vegan, Beef'],
                [u'Tower', u'Friday', u'Composed Salad Bar', u'Qunioa Salad-V'],
                [u'Tower', u'Saturday', u'Continental Breakfast', u'Steel Cut Oatmeal-V'],
                [u'Tower', u'Saturday', u'Homestyle Dinner', u'Marinara/Alfredo'],
                [u'Tower', u'Sunday', u'Brunch', u'Red Bliss Home Fries-V'],
                [u'Tower', u'Sunday', u'Pasta', u'Vegan Hot Dogs'],
                [u'Bae Pao Lu Chow',
                 u'Tuesday',
                 u'Continental Breakfast',
                 u'Yogurt & Cottage Cheese'],
                [u'Bae Pao Lu Chow', u'Tuesday', u'Pizza', u'Apple Pizza'],
                [u'Bae Pao Lu Chow', u'Tuesday', u'Deli', u'Roast Beef'],
                [u'Bae Pao Lu Chow', u'Wednesday', u'Soup', u'Chicken Barley'],
                [u'Bae Pao Lu Chow', u'Wednesday', u'Fusion Lunch', u'Crescent Roll'],
                [u'Bae Pao Lu Chow', u'Wednesday', u'Deli', u'Seafood Salad'],
                [u'Bae Pao Lu Chow', u'Thursday', u'Continental Breakfast', u'Fresh Fruit'],
                [u'Bae Pao Lu Chow', u'Thursday', u'Pure', u'Black Bean Salsa'],
                [u'Bae Pao Lu Chow', u'Friday', u'Continental Breakfast', u'Waffle Bar'],
                [u'Bae Pao Lu Chow', u'Friday', u'Grill', u'Jojo Fries'],
                [u'Bae Pao Lu Chow', u'Friday', u'Homestyle Dinner', u'Green Bean Casserole'],
                [u'Bae Pao Lu Chow', u'Saturday', u'Soup', u'New England Clam'],
                [u'Bae Pao Lu Chow', u'Saturday', u'Fusion Lunch', u"O'brian Potatoes"],
                [u'Bae Pao Lu Chow', u'Sunday', u'Continental Breakfast', u'Oatmeal Bar'],
                [u'Bae Pao Lu Chow', u'Sunday', u'Deli MYO', u'Sliced Turkey'],
                [u'Bates', u'Monday', u'Breakfast', u'Hardboiled Eggs-Veg'],
                [u'Bates', u'Monday', u'Homestyle Lunch', u'Sesame Nappa Cabbage'],
                [u'Bates', u'Tuesday', u'Homestyle Lunch', u'Steamed White Rice'],
                [u'Bates', u'Tuesday', u'Pasta', u'Lo Mein Noodles'],
                [u'Bates', u'Wednesday', u'Breakfast', u'Waffle Station-Veg'],
                [u'Bates', u'Thursday', u'Global Grill', u'Potato Perogies'],
                [u'Bates', u'Thursday', u'Pasta', u'Marinara'],
                [u'Bates', u'Thursday', u'Deli', u'3 Cheeses-Veg'],
                [u'Bates', u'Friday', u'Breakfast', u'Steel Cut Oatmeal'],
                [u'Bates', u'Friday', u'Homestyle Dinner', u'Zucchini & Summer Squash'],
                [u'Bates', u'Friday', u'Deli', u'Turkey, Roast Beef'],
                [u'Bates', u'Saturday', u'Brunch Homestyle', u'Spanish Rice'],
                [u'Bates', u'Saturday', u'Global Grill', u'Myo Grilled Cheese'],
                [u'Bates', u'Sunday', u'Brunch Homestyle', u'Beef & Chicken Meatballs'],
                [u'Pomeroy', u'Monday', u'Breakfast', u'Scrambled Eggs'],
                [u'Pomeroy', u'Monday', u'Soup of the Day', u'Pumpkin Soup'],
                [u'Pomeroy', u'Monday', u'Lunch', u'Brown Rice'],
                [u'Pomeroy', u'Tuesday', u'Pasta Bar', u'Sauce'],
                [u'Pomeroy', u'Tuesday', u'Dinner', u'Spinach'],
                [u'Pomeroy', u'Wednesday', u'Breakfast', u'Fresh Fruit'],
                [u'Pomeroy', u'Wednesday', u'Lunch', u'Vegetable & Chicken'],
                [u'Pomeroy', u'Thursday', u'Breakfast', u'Yogurts'],
                [u'Pomeroy', u'Thursday', u'Lunch', u'Spaghetti & Meat Sauce'],
                [u'Pomeroy', u'Friday', u'Deli', u'Roasted Vegetables'],
                [u'Pomeroy', u'Saturday', u'Brunch', u'Mash Potatoes'],
                [u'Pomeroy', u'Sunday', u'Continental Breakfast', u'Fresh Fruit'],
                [u'Pomeroy', u'Sunday', u'Deli', u'Tabbouleh'],
                [u'Stone Davis', u'Monday', u'Pizza', u'Cheese'],
                [u'Stone Davis', u'Tuesday', u'Lunch', u'Carrots'],
                [u'Stone Davis', u'Tuesday', u'Pizza', u'Buffalo Chicken'],
                [u'Stone Davis', u'Wednesday', u'Breakfast', u'Hard Boiled Eggs'],
                [u'Stone Davis', u'Wednesday', u'Lunch', u'Veggie Lo Mien'],
                [u'Stone Davis', u'Wednesday', u'Pizza', u'Cheese Steak'],
                [u'Stone Davis', u'Wednesday', u'Davis Grille', u'Classic Grilled Cheese'],
                [u'Stone Davis', u'Thursday', u'Breakfast', u'Turkey Sausage Links'],
                [u'Stone Davis', u'Thursday', u'Soup', u'Chicken Noodle'],
                [u'Stone Davis', u'Thursday', u'Pasta', u'Rice'],
                [u'Stone Davis', u'Friday', u'Breakfast', u'Steel Cut Oats Bar (V)'],
                [u'Stone Davis', u'Friday', u'Soup', u'Manhattan Clam'],
                [u'Tower', u'Monday', u'Pizza/Pasta', u'Puttanesca Sauce-V'],
                [u'Tower', u'Monday', u'Fusions', u'Fresh Herbs'],
                [u'Tower', u'Tuesday', u'Homestyle Lunch', u'Baked Ziti'],
                [u'Tower', u'Tuesday', u'Pizza/Pasta', u'Garlic Butter Sauce'],
                [u'Tower', u'Tuesday', u'Fusions', u'Shredded Cheese'],
                [u'Tower', u'Wednesday', u'Breakfast', u'Fresh Sliced Fruit-V'],
                [u'Tower', u'Wednesday', u'Vegan & Grain Bar', u'Green Lentils'],
                [u'Tower', u'Wednesday', u'Deli', u'Turkey, Ham, Salami'],
                [u'Tower', u'Thursday', u'Breakfast', u'Fresh Sliced Fruit-V'],
                [u'Tower', u'Thursday', u'Vegan & Grain Bar', u'Brown Rice Pilaf'],
                [u'Tower', u'Thursday', u'Deli', u'Turkey, Ham, Egg Salad'],
                [u'Tower', u'Friday', u'Breakfast', u'Waffle Bar-V'],
                [u'Tower', u'Friday', u'Pizza/Pasta', u'Marinara Sauce'],
                [u'Tower', u'Saturday', u'Brunch', u'Scrambled Eggs'],
                [u'Tower', u'Saturday', u'Homestyle Dinner', u'Carrots-V'],
                [u'Tower', u'Sunday', u'Brunch', u'Beef Steaks'],
                [u'Tower', u'Sunday', u'Vegan & Grain Bar', u'Whole Wheat Spagetti & Pesto'],
                [u'Tower', u'Sunday', u'Pasta', u'Beef Chili'],
                [u'Bae Pao Lu Chow', u'Tuesday', u'Pizza', u"Chef's Daily Artisan"],
                [u'Bae Pao Lu Chow', u'Tuesday', u'Homestyle Dinner', u'Beef Meat Loaf'],
                [u'Bae Pao Lu Chow', u'Thursday', u'Pizza', u'White Pizza'],
                [u'Bae Pao Lu Chow', u'Thursday', u'Fusion Lunch', u'Okra & Tomatoes'],
                [u'Bae Pao Lu Chow', u'Friday', u'Soup', u'Butternut Squash &'],
                [u'Bae Pao Lu Chow', u'Friday', u'Fusion Lunch', u'Rotisserie Chicken'],
                [u'Bae Pao Lu Chow', u'Sunday', u'Soup', u'Pumpkin Soup'],
                [u'Bae Pao Lu Chow', u'Sunday', u'Grill', u'Falafel & Hummus'],
                [u'Bae Pao Lu Chow', u'Sunday', u'Fusion Lunch', u'Bacon'],
                [u'Bates', u'Monday', u'Global Grill', u'Veggie Fajitas'],
                [u'Bates', u'Tuesday', u'Breakfast', u'Waffle Station-Veg'],
                [u'Bates', u'Tuesday', u'Homestyle Dinner', u'Green Beans'],
                [u'Bates', u'Tuesday', u'Fusion', u'Crunchy Tacos'],
                [u'Bates', u'Wednesday', u'Homestyle Lunch', u'Blackened Catfish'],
                [u'Bates', u'Wednesday', u'Homestyle Dinner', u'Roasted Zucchini'],
                [u'Bates', u'Wednesday', u'Deli', u'Chicken Salad'],
                [u'Bates', u'Thursday', u'Global Grill', u'Potato Pancakes'],
                [u'Bates', u'Friday', u'Breakfast', u'Scrambled Eggs Or Whites-Veg'],
                [u'Bates', u'Saturday', u'Fusion', u'Closed'],
                [u'Bates', u'Sunday', u'Brunch Grill', u'Myo Omelete'],
                [u'Bates', u'Sunday', u'Deli', u'Chefs Choice'],
                [u'Pomeroy', u'Monday', u'Deli', u'Cheese of the Day'],
                [u'Pomeroy', u'Monday', u'Dinner', u'Herbed Tofu'],
                [u'Pomeroy', u'Tuesday', u'Breakfast', u'Oatmeal Bar'],
                [u'Pomeroy', u'Tuesday', u'Deli', u'Hummus'],
                [u'Pomeroy', u'Wednesday', u'Breakfast', u'Egg Whites Upon Request'],
                [u'Pomeroy', u'Wednesday', u'Soup of the Day', u'Soup'],
                [u'Pomeroy', u'Wednesday', u'Dinner', u'Crunchy Pappardelle'],
                [u'Pomeroy', u'Thursday', u'Soup of the Day', u'Bean Soup 202'],
                [u'Pomeroy', u'Thursday', u'Dinner', u'Quiche'],
                [u'Pomeroy', u'Friday', u'Breakfast', u'Oatmeal Bar'],
                [u'Pomeroy', u'Friday', u'Lunch', u'Brown Rice'],
                [u'Pomeroy', u'Saturday', u'Continental Breakfast', u'Belgian Waffle Bar'],
                [u'Pomeroy', u'Saturday', u'Brunch', u'Glazed Carrots'],
                [u'Pomeroy', u'Sunday', u'Continental Breakfast', u'Fresh Fruit'],
                [u'Stone Davis', u'Monday', u'Breakfast', u'Waffle Bar'],
                [u'Stone Davis', u'Monday', u'Dinner', u'Apple Brined Turkey Breast'],
                [u'Stone Davis', u'Monday', u'Davis Grille', u'Hot Dog Bar'],
                [u'Stone Davis', u'Tuesday', u'Breakfast', u'Scrambled Eggs'],
                [u'Stone Davis', u'Tuesday', u'Dinner', u'Japanese Slaw'],
                [u'Stone Davis', u'Tuesday', u'Davis Grille', u'Homemade Chicken Nuggets'],
                [u'Stone Davis', u'Wednesday', u'Breakfast', u'Waffle Bar'],
                [u'Stone Davis', u'Wednesday', u'Dinner', u'Beef Lasagna'],
                [u'Stone Davis', u'Wednesday', u'Pizza', u'Sausage'],
                [u'Stone Davis', u'Wednesday', u'MYO Deli', u'Cheese'],
                [u'Stone Davis', u'Thursday', u'Lunch', u'Cider Cooked Cabbage'],
                [u'Stone Davis', u'Thursday', u'Pizza', u'Vegan Veg'],
                [u'Stone Davis', u'Thursday', u'MYO Deli', u'Cheese'],
                [u'Stone Davis', u'Friday', u'Lunch', u'Acorn Squash'],
                [u'Stone Davis', u'Friday', u'Davis Grille', u'Black Bean Burger'],
                [u'Tower', u'Monday', u'Breakfast', u'Egg & Cheese Muffin'],
                [u'Tower', u'Monday', u'Homestyle Dinner', u'Spinach'],
                [u'Tower', u'Monday', u'Grill', u'Production Day'],
                [u'Tower', u'Tuesday', u'Breakfast', u'Hard Boiled Eggs'],
                [u'Tower', u'Tuesday', u'Homestyle Dinner', u'Vietnamese Roast Pork'],
                [u'Tower', u'Tuesday', u'Grill', u'French Fries'],
                [u'Tower', u'Tuesday', u'Allergy Station', u'Roast Pork-Dinner'],
                [u'Tower', u'Wednesday', u'Homestyle Dinner', u'Chicken & Sausage Gumbo'],
                [u'Tower', u'Wednesday', u'Composed Salad Bar', u'Caesar Salad-Veg'],
                [u'Tower', u'Thursday', u'Breakfast', u'Hard Boiled Eggs'],
                [u'Tower', u'Thursday', u'Homestyle Dinner', u'Scrambled Eggs'],
                [u'Tower', u'Thursday', u'Composed Salad Bar', u'Chef Salaf'],
                [u'Tower', u'Thursday', u'Allergy Station', u'Breakfast-Dinner'],
                [u'Tower', u'Friday', u'Homestyle Lunch', u'Steamed Red Potatoes'],
                [u'Tower', u'Friday', u'Deli', u'Lettuce, Tomato, Onion, Pickles'],
                [u'Tower', u'Saturday', u'Brunch', u'Pork Bacon'],
                [u'Tower', u'Saturday', u'Vegan & Grain Bar', u'Closed'],
                [u'Tower', u'Sunday', u'Continental Breakfast', u'Waffle Bar-V'],
                [u'Tower', u'Sunday', u'Homestyle Dinner', u'Roast Turkey Breast'],
                [u'Tower', u'Sunday', u'Allergy Station', u'Roast Turkey-Dinner']
               ]
